# Generated by Django 3.0.3 on 2020-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='post_token',
            field=models.CharField(default='', max_length=300),
        ),
    ]
