# Generated by Django 3.0.3 on 2020-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vkuser_post_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='shutterstock_token',
            field=models.CharField(default='', max_length=300),
        ),
    ]
