# Generated by Django 3.0.3 on 2020-11-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vkuser_shutterstock_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='shutterstock_token',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
