# Generated by Django 3.0.3 on 2020-12-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vkuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='post_token',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='shutterstock_token',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(default=-1)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='users.VkUser')),
            ],
        ),
    ]
