# Generated by Django 3.0.3 on 2020-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201224_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
