# Generated by Django 3.0.3 on 2021-01-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201224_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=' ')),
                ('service_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
