# Generated by Django 3.0.3 on 2021-01-28 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_serviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='date_until',
            field=models.DateField(default=datetime.date(2021, 5, 3)),
        ),
    ]
