# Generated by Django 3.0.3 on 2021-05-30 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_servicerequest_date_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='date_shutter_banned',
            field=models.DateField(default=datetime.date(2009, 5, 3)),
        ),
    ]
