# Generated by Django 3.0.3 on 2020-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='', max_length=200)),
                ('number_of_moderators', models.IntegerField(default=0)),
                ('code', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FutureModerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(default='', max_length=200)),
                ('role', models.CharField(default='', max_length=200)),
                ('group_id', models.CharField(default='', max_length=200)),
                ('is_contact', models.IntegerField(default=0)),
            ],
        ),
    ]
