# Generated by Django 3.0.3 on 2020-12-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201107_1601'),
        ('group_copy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_group_owner', to='users.VkUser'),
        ),
    ]
