# Generated by Django 3.0.3 on 2021-08-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_vkuser_medals'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.TextField(default='[]')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vk_user_ok', to='users.VkUser')),
            ],
        ),
    ]
