# Generated by Django 3.0.3 on 2021-06-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_vkuser_date_shutter_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(default='[]')),
                ('key', models.CharField(default='f', max_length=600)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to='users.VkUser')),
            ],
        ),
    ]
