# Generated by Django 3.0.3 on 2020-10-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.VkUser')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='users.VkUser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(default=0)),
                ('owner_id', models.BigIntegerField(default=0)),
                ('owner_name', models.CharField(default='Не указано', max_length=1000)),
                ('owner_img_link', models.CharField(default='Не указано', max_length=1000)),
                ('from_id', models.BigIntegerField(default=0)),
                ('date', models.CharField(default='Не указано', max_length=300)),
                ('text', models.CharField(default='Не указано', max_length=30000)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('reposts_count', models.BigIntegerField(default=0)),
                ('views_count', models.BigIntegerField(default=0)),
                ('attachments', models.CharField(default='Не указано', max_length=30000)),
                ('date_added', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vkuser_id', to='users.VkUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=300)),
                ('date', models.CharField(default='', max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='think_bank.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='users.VkUser')),
            ],
        ),
    ]
