# Generated by Django 3.0.3 on 2021-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medal',
            name='description',
        ),
        migrations.AddField(
            model_name='medal',
            name='description_copper',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='medal',
            name='description_diamond',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='medal',
            name='description_gold',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='medal',
            name='description_silver',
            field=models.CharField(default='', max_length=400),
        ),
    ]
