# Generated by Django 3.0.3 on 2021-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20210415_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='h_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='w_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='x_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='y_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='h_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='is_dev',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='w_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='x_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='y_p',
            field=models.IntegerField(default=0),
        ),
    ]
