# Generated by Django 3.0.3 on 2021-07-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_vkuser_medals'),
        ('charts', '0007_auto_20210416_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='secondary_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_secondary_user', to='users.VkUser'),
        ),
    ]
