# Generated by Django 3.0.3 on 2021-09-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBankUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_written', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='{}')),
                ('fwd_body', models.TextField(default='[]')),
            ],
        ),
    ]
