# Generated by Django 3.0.3 on 2021-09-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_vkuser_medals'),
        ('message_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBankRepostPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vk_user_message_bank_permission', to='users.VkUser')),
            ],
        ),
    ]
