# Generated by Django 3.0.3 on 2020-11-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_vkuser_post_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShutterstockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shutterstock_token', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shutterstock_vk_user', to='users.VkUser')),
            ],
        ),
    ]
