# Generated by Django 3.0.3 on 2021-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotostockAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=50)),
                ('stock_type', models.IntegerField(default=-1)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
