# Generated by Django 3.0.3 on 2021-05-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_vkuser_date_shutter_banned'),
        ('shutterstock', '0004_auto_20210225_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownloadRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.TextField(default='[]')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='users.VkUser')),
            ],
        ),
    ]
