# Generated by Django 3.0.3 on 2021-07-16 07:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_vkuser_medals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDuplicateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='[]')),
                ('in_progress', models.BooleanField(default=False)),
                ('last_updated', models.DateField(default=datetime.date(2021, 3, 24))),
                ('progress', models.CharField(default='', max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_duplicate_job_owner', to='users.VkUser')),
            ],
        ),
    ]
