# Generated by Django 3.0.3 on 2021-03-24 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectTagsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('in_progress', models.BooleanField(default=False)),
                ('last_updated', models.DateField(default=datetime.date(2021, 3, 24))),
            ],
        ),
    ]
