# Generated by Django 3.0.3 on 2021-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_collecttagsjob_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttagsjob',
            name='progress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
