# Generated by Django 3.0.3 on 2021-07-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_vkuser_medals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('data', models.TextField(default='')),
                ('title', models.CharField(default='Не указано', max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_table_vk_user', to='users.VkUser')),
            ],
        ),
    ]
