# Generated by Django 3.0.3 on 2020-10-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('scheduler', '0002_auto_20201027_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpost',
            name='target_groups',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_poster', to='users.VkUser'),
        ),
    ]
