# Generated by Django 3.0.3 on 2020-10-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('scheduler', '0003_auto_20201027_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=600)),
                ('group_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='plannedpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_poster', to='users.VkUser'),
        ),
        migrations.AlterField(
            model_name='plannedpost',
            name='target_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_post', to='scheduler.AvailableGroup'),
        ),
    ]
