# Generated by Django 3.0.3 on 2020-10-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20201027_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablegroup',
            name='group_img',
            field=models.CharField(default='', max_length=600),
        ),
    ]
