# Generated by Django 3.0.3 on 2020-10-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('scheduler', '0005_availablegroup_group_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedpost',
            name='target_groups',
        ),
        migrations.RemoveField(
            model_name='plannedpost',
            name='user',
        ),
        migrations.AddField(
            model_name='availablegroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='users.VkUser'),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='close_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='from_group',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='mark_as_ads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='mute_notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='target_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_group', to='scheduler.AvailableGroup'),
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=4000)),
                ('attachments', models.CharField(max_length=4000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='users.VkUser')),
            ],
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_post', to='scheduler.SavedPost'),
        ),
    ]
