# Generated by Django 3.0.3 on 2020-11-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_successpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessFailPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_old_post', to='scheduler.SavedPost')),
                ('target_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_old_group', to='scheduler.AvailableGroup')),
            ],
        ),
        migrations.DeleteModel(
            name='SuccessPost',
        ),
    ]
