# Generated by Django 3.0.3 on 2020-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20201102_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedpost',
            name='target_group',
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='posted_vk_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='target_groups_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='SuccessFailPost',
        ),
    ]
