# Generated by Django 3.0.3 on 2020-11-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20201103_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedpost',
            old_name='post_date',
            new_name='timezone',
        ),
    ]
