# Generated by Django 3.0.3 on 2020-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20201103_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpost',
            name='days_add',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='days_delete',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='every_day_marker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='time_add',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='time_delete',
            field=models.CharField(default='', max_length=100),
        ),
    ]
