# Generated by Django 3.0.3 on 2020-11-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20201103_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedpost',
            name='timezone',
        ),
    ]
