# Generated by Django 3.0.3 on 2020-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20201104_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpost',
            name='last_day_added',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='last_day_deleted',
            field=models.IntegerField(default=-1),
        ),
    ]
